import tw from 'twrnc'
import { IBaseTheme, IColours } from './interfaces'

export const BaseTheme: IBaseTheme = {
  cursor: {
    pointer: tw`cursor-pointer`,
    default: tw`cursor-default`,
  },
  aspectRatio: {
    square: tw`aspect-square`,
    widescreen: tw`aspect-video`,
    // auto: tw`aspect-auto`,
  },
  overflow: {
    visible: tw`overflow-visible`,
    hidden: tw`overflow-hidden`,
    scroll: tw`overflow-scroll`,
  },
  height: {
    fitContent: {
      height: "fit-content"
    },
    // auto: tw`h-auto`,
    full: tw`h-full`,
    half: tw`h-1/2`,
    third: tw`h-1/3`,
    quarter: tw`h-1/4`,
    oneColumn: tw`h-1/12`,
    twoColumn: tw`h-2/12`,
    threeColumn: tw`h-3/12`,
    fourColumn: tw`h-4/12`,
    fiveColumn: tw`h-5/12`,
    sixColumn: tw`h-6/12`,
    sevenColumn: tw`h-7/12`,
    eightColumn: tw`h-8/12`,
    nineColumn: tw`h-9/12`,
    tenColumn: tw`h-10/12`,
    elevenColumn: tw`h-11/12`,
    twelveColumn: tw`h-12/12`,
  },
  minHeight: {
    fitContent: tw`h-min`,
    // auto: tw`min-h-auto`,
    full: tw`min-h-full`,
    half: tw`min-h-1/2`,
    third: tw`min-h-1/3`,
    quarter: tw`min-h-1/4`,
    oneColumn: tw`min-h-1/12`,
    twoColumn: tw`min-h-2/12`,
    threeColumn: tw`min-h-3/12`,
    fourColumn: tw`min-h-4/12`,
    fiveColumn: tw`min-h-5/12`,
    sixColumn: tw`min-h-6/12`,
    sevenColumn: tw`min-h-7/12`,
    eightColumn: tw`min-h-8/12`,
    nineColumn: tw`min-h-9/12`,
    tenColumn: tw`min-h-10/12`,
    elevenColumn: tw`min-h-11/12`,
    twelveColumn: tw`min-h-12/12`,
  },
  maxHeight: {
    fitContent: tw`h-max`,
    // auto: tw`max-h-auto`,
    full: tw`max-h-full`,
    half: tw`max-h-1/2`,
    third: tw`max-h-1/3`,
    quarter: tw`max-h-1/4`,
    oneColumn: tw`max-h-1/12`,
    twoColumn: tw`max-h-2/12`,
    threeColumn: tw`max-h-3/12`,
    fourColumn: tw`max-h-4/12`,
    fiveColumn: tw`max-h-5/12`,
    sixColumn: tw`max-h-6/12`,
    sevenColumn: tw`max-h-7/12`,
    eightColumn: tw`max-h-8/12`,
    nineColumn: tw`max-h-9/12`,
    tenColumn: tw`max-h-10/12`,
    elevenColumn: tw`max-h-11/12`,
    twelveColumn: tw`max-h-12/12`,
  },
  width: {
    fitContent: tw`w-fit`,
    // auto: tw`w-auto`,
    full: tw`w-full`,
    half: tw`w-1/2`,
    third: tw`w-1/3`,
    quarter: tw`w-1/4`,
    oneColumn: tw`w-1/12`,
    twoColumn: tw`w-2/12`,
    threeColumn: tw`w-3/12`,
    fourColumn: tw`w-4/12`,
    fiveColumn: tw`w-5/12`,
    sixColumn: tw`w-6/12`,
    sevenColumn: tw`w-7/12`,
    eightColumn: tw`w-8/12`,
    nineColumn: tw`w-9/12`,
    tenColumn: tw`w-10/12`,
    elevenColumn: tw`w-11/12`,
    twelveColumn: tw`w-12/12`,
  },
  minWidth: {
    fitContent: tw`w-min`,
    // auto: tw`min-w-auto`,
    full: tw`min-w-full`,
    half: tw`min-w-1/2`,
    third: tw`min-w-1/3`,
    quarter: tw`min-w-1/4`,
    oneColumn: tw`min-w-1/12`,
    twoColumn: tw`min-w-2/12`,
    threeColumn: tw`min-w-3/12`,
    fourColumn: tw`min-w-4/12`,
    fiveColumn: tw`min-w-5/12`,
    sixColumn: tw`min-w-6/12`,
    sevenColumn: tw`min-w-7/12`,
    eightColumn: tw`min-w-8/12`,
    nineColumn: tw`min-w-9/12`,
    tenColumn: tw`min-w-10/12`,
    elevenColumn: tw`min-w-11/12`,
    twelveColumn: tw`min-w-12/12`,
  },
  maxWidth: {
    fitContent: tw`w-max`,
    // auto: tw`max-w-auto`,
    full: tw`max-w-full`,
    half: tw`max-w-1/2`,
    third: tw`max-w-1/3`,
    quarter: tw`max-w-1/4`,
    oneColumn: tw`max-w-1/12`,
    twoColumn: tw`max-w-2/12`,
    threeColumn: tw`max-w-3/12`,
    fourColumn: tw`max-w-4/12`,
    fiveColumn: tw`max-w-5/12`,
    sixColumn: tw`max-w-6/12`,
    sevenColumn: tw`max-w-7/12`,
    eightColumn: tw`max-w-8/12`,
    nineColumn: tw`max-w-9/12`,
    tenColumn: tw`max-w-10/12`,
    elevenColumn: tw`max-w-11/12`,
    twelveColumn: tw`max-w-12/12`,
  },
  border: {
    radius: {
      all: {
        none: tw`rounded-none`,
        small: tw`rounded-md`,
        medium: tw`rounded-xl`,
        large: tw`rounded-2xl`,
        xlarge: tw`rounded-3xl`,
        rounded: tw`rounded-full`,
      },
      top: {
        none: tw`rounded-t-none`,
        small: tw`rounded-t-md`,
        medium: tw`rounded-t-xl`,
        large: tw`rounded-t-2xl`,
        xlarge: tw`rounded-t-3xl`,
        rounded: tw`rounded-t-full`,
      },
      bottom: {
        none: tw`rounded-b-none`,
        small: tw`rounded-b-md`,
        medium: tw`rounded-b-xl`,
        large: tw`rounded-b-2xl`,
        xlarge: tw`rounded-b-3xl`,
        rounded: tw`rounded-b-full`,
      },
      left: {
        none: tw`rounded-l-none`,
        small: tw`rounded-l-md`,
        medium: tw`rounded-l-xl`,
        large: tw`rounded-l-2xl`,
        xlarge: tw`rounded-l-3xl`,
        rounded: tw`rounded-l-full`,
      },
      right: {
        none: tw`rounded-r-none`,
        small: tw`rounded-r-md`,
        medium: tw`rounded-r-xl`,
        large: tw`rounded-r-2xl`,
        xlarge: tw`rounded-r-3xl`,
        rounded: tw`rounded-r-full`,
      },
      topLeft: {
        none: tw`rounded-tl-none`,
        small: tw`rounded-tl-md`,
        medium: tw`rounded-tl-xl`,
        large: tw`rounded-tl-2xl`,
        xlarge: tw`rounded-tl-3xl`,
        rounded: tw`rounded-tl-full`,
      },
      topRight: {
        none: tw`rounded-tr-none`,
        small: tw`rounded-tr-md`,
        medium: tw`rounded-tr-xl`,
        large: tw`rounded-tr-2xl`,
        xlarge: tw`rounded-tr-3xl`,
        rounded: tw`rounded-tr-full`,
      },
      bottomLeft: {
        none: tw`rounded-bl-none`,
        small: tw`rounded-bl-md`,
        medium: tw`rounded-bl-xl`,
        large: tw`rounded-bl-2xl`,
        xlarge: tw`rounded-bl-3xl`,
        rounded: tw`rounded-bl-full`,
      },
      bottomRight: {
        none: tw`rounded-br-none`,
        small: tw`rounded-br-md`,
        medium: tw`rounded-br-xl`,
        large: tw`rounded-br-2xl`,
        xlarge: tw`rounded-br-3xl`,
        rounded: tw`rounded-br-full`,
      },
    },
    width: {
      all: {
        none: tw`border-0`,
        thin: tw`border`,
        medium: tw`border-2`,
        thick: tw`border-4`,
      },
      top: {
        none: tw`border-t-0`,
        thin: tw`border-t`,
        medium: tw`border-t-2`,
        thick: tw`border-t-4`,
      },
      bottom: {
        none: tw`border-b-0`,
        thin: tw`border-b`,
        medium: tw`border-b-2`,
        thick: tw`border-b-4`,
      },
      left: {
        none: tw`border-l-0`,
        thin: tw`border-l`,
        medium: tw`border-l-2`,
        thick: tw`border-l-4`,
      },
      right: {
        none: tw`border-r-0`,
        thin: tw`border-r`,
        medium: tw`border-r-2`,
        thick: tw`border-r-4`,
      },
      horizontal: {
        none: tw`border-l-0 border-r-0`,
        thin: tw`border-l border-r`,
        medium: tw`border-l-2 border-r-2`,
        thick: tw`border-l-4 border-r-4`,
      },
      vertical: {
        none: tw`border-t-0 border-b-0`,
        thin: tw`border-t border-b`,
        medium: tw`border-t-2 border-b-2`,
        thick: tw`border-t-4 border-b-4`,
      },
    },
  },
  flex: {
    flex: tw`flex`,
    grow: tw`flex-grow`,
    shrink: tw`flex-shrink`,
    direction: {
      row: tw`flex-row`,
      column: tw`flex-col`,
    },
    wrap: tw`flex-wrap`,
    alignItems: {
      start: tw`items-start`,
      center: tw`items-center`,
      end: tw`items-end`,
    },
    alignContent: {
      start: tw`content-start`,
      center: tw`content-center`,
      end: tw`content-end`,
    },
    justifyContent: {
      start: tw`justify-start`,
      center: tw`justify-center`,
      end: tw`justify-end`,
      between: tw`justify-between`,
      evenly: tw`justify-evenly`,
    },
    basis: {
      // auto: {
      //   flexBasis: 'auto',
      // },
      half: {
        flexBasis: '50%',
      },
      quarter: {
        flexBasis: '25%',
      },
      third: {
        flexBasis: '33%',
      },
      oneColumn: {
        flexBasis: '8.333333%',
      },
      twoColumn: {
        flexBasis: '16.666667%',
      },
      threeColumn: {
        flexBasis: '25%',
      },
      fourColumn: {
        flexBasis: '33.333333%',
      },
      fiveColumn: {
        flexBasis: '41.666667%',
      },
      sixColumn: {
        flexBasis: '50%',
      },
      sevenColumn: {
        flexBasis: '58.333333%',
      },
      eightColumn: {
        flexBasis: '66.666667%',
      },
      nineColumn: {
        flexBasis: '75%',
      },
      tenColumn: {
        flexBasis: '83.333333%',
      },
      elevenColumn: {
        flexBasis: '91.666667%',
      },
      twelveColumn: {
        flexBasis: '100%',
      },
      full: {
        flexBasis: '100%',
      },
    },
    alignSelf: {
      start: tw`self-start`,
      center: tw`self-center`,
      end: tw`self-end`,
    },
  },
  font: {
    alignment: {
      center: tw`text-center`,
      left: tw`text-left`,
      right: tw`text-right`,
    },
    size: {
      smallest: tw`text-xs`,
      xxxxsmall: tw`text-sm`,
      xxxsmall: tw`text-base`,
      xxsmall: tw`text-lg`,
      xsmall: tw`text-xl`,
      small: tw`text-2xl`,
      medium: tw`text-3xl`,
      large: tw`text-4xl`,
    },
    weight: {
      bold: {
        fontFamily: 'SpartanBold',
      },
      extraBold: {
        fontFamily: 'SpartanExtraBold',
      },
      extraLight: {
        fontFamily: 'SpartanExtraLight',
      },
      light: {
        fontFamily: 'SpartanLight',
      },
      medium: {
        fontFamily: 'SpartanMedium',
      },
      regular: {
        fontFamily: 'SpartanRegular',
      },
      semiBold: {
        fontFamily: 'SpartanSemiBold',
      },
      semiLight: {
        fontFamily: 'SpartanSemiLight',
      },
      thin: {
        fontFamily: 'SpartanThin',
      },
    },
  },
  margin: {
    top: {
      none: tw`mt-0`,
      xxxsmall: tw`mt-1`,
      xxsmall: tw`mt-2`,
      xsmall: tw`mt-3`,
      small: tw`mt-4`,
      medium: tw`mt-5`,
      large: tw`mt-6`,
      xlarge: tw`mt-7`,
      xxlarge: tw`mt-8`,
      xxxlarge: tw`mt-9`,
    },
    right: {
      none: tw`mr-0`,
      xxxsmall: tw`mr-1`,
      xxsmall: tw`mr-2`,
      xsmall: tw`mr-3`,
      small: tw`mr-4`,
      medium: tw`mr-5`,
      large: tw`mr-6`,
      xlarge: tw`mr-7`,
      xxlarge: tw`mr-8`,
      xxxlarge: tw`mr-9`,
    },
    bottom: {
      none: tw`mb-0`,
      xxxsmall: tw`mb-1`,
      xxsmall: tw`mb-2`,
      xsmall: tw`mb-3`,
      small: tw`mb-4`,
      medium: tw`mb-5`,
      large: tw`mb-6`,
      xlarge: tw`mb-7`,
      xxlarge: tw`mb-8`,
      xxxlarge: tw`mb-9`,
    },
    left: {
      none: tw`ml-0`,
      xxxsmall: tw`ml-1`,
      xxsmall: tw`ml-2`,
      xsmall: tw`ml-3`,
      small: tw`ml-4`,
      medium: tw`ml-5`,
      large: tw`ml-6`,
      xlarge: tw`ml-7`,
      xxlarge: tw`ml-8`,
      xxxlarge: tw`ml-9`,
    },
    all: {
      none: tw`m-0`,
      xxxsmall: tw`m-1`,
      xxsmall: tw`m-2`,
      xsmall: tw`m-3`,
      small: tw`m-4`,
      medium: tw`m-5`,
      large: tw`m-6`,
      xlarge: tw`m-7`,
      xxlarge: tw`m-8`,
      xxxlarge: tw`m-9`,
    },
    horizontal: {
      none: tw`mx-0`,
      xxxsmall: tw`mx-1`,
      xxsmall: tw`mx-2`,
      xsmall: tw`mx-3`,
      small: tw`mx-4`,
      medium: tw`mx-5`,
      large: tw`mx-6`,
      xlarge: tw`mx-7`,
      xxlarge: tw`mx-8`,
      xxxlarge: tw`mx-9`,
    },
    vertical: {
      none: tw`my-0`,
      xxxsmall: tw`my-1`,
      xxsmall: tw`my-2`,
      xsmall: tw`my-3`,
      small: tw`my-4`,
      medium: tw`my-5`,
      large: tw`my-6`,
      xlarge: tw`my-7`,
      xxlarge: tw`my-8`,
      xxxlarge: tw`my-9`,
    },
  },
  padding: {
    top: {
      none: tw`pt-0`,
      xxxsmall: tw`pt-1`,
      xxsmall: tw`pt-2`,
      xsmall: tw`pt-3`,
      small: tw`pt-4`,
      medium: tw`pt-5`,
      large: tw`pt-6`,
      xlarge: tw`pt-7`,
      xxlarge: tw`pt-8`,
      xxxlarge: tw`pt-9`,
    },
    right: {
      none: tw`pr-0`,
      xxxsmall: tw`pr-1`,
      xxsmall: tw`pr-2`,
      xsmall: tw`pr-3`,
      small: tw`pr-4`,
      medium: tw`pr-5`,
      large: tw`pr-6`,
      xlarge: tw`pr-7`,
      xxlarge: tw`pr-8`,
      xxxlarge: tw`pr-9`,
    },
    bottom: {
      none: tw`pb-0`,
      xxxsmall: tw`pb-1`,
      xxsmall: tw`pb-2`,
      xsmall: tw`pb-3`,
      small: tw`pb-4`,
      medium: tw`pb-5`,
      large: tw`pb-6`,
      xlarge: tw`pb-7`,
      xxlarge: tw`pb-8`,
      xxxlarge: tw`pb-9`,
    },
    left: {
      none: tw`pl-0`,
      xxxsmall: tw`pl-1`,
      xxsmall: tw`pl-2`,
      xsmall: tw`pl-3`,
      small: tw`pl-4`,
      medium: tw`pl-5`,
      large: tw`pl-6`,
      xlarge: tw`pl-7`,
      xxlarge: tw`pl-8`,
      xxxlarge: tw`pl-9`,
    },
    all: {
      none: tw`p-0`,
      xxxsmall: tw`p-1`,
      xxsmall: tw`p-2`,
      xsmall: tw`p-3`,
      small: tw`p-4`,
      medium: tw`p-5`,
      large: tw`p-6`,
      xlarge: tw`p-7`,
      xxlarge: tw`p-8`,
      xxxlarge: tw`p-9`,
    },
    horizontal: {
      none: tw`px-0`,
      xxxsmall: tw`px-1`,
      xxsmall: tw`px-2`,
      xsmall: tw`px-3`,
      small: tw`px-4`,
      medium: tw`px-5`,
      large: tw`px-6`,
      xlarge: tw`px-7`,
      xxlarge: tw`px-8`,
      xxxlarge: tw`px-9`,
    },
    vertical: {
      none: tw`py-0`,
      xxxsmall: tw`py-1`,
      xxsmall: tw`py-2`,
      xsmall: tw`py-3`,
      small: tw`py-4`,
      medium: tw`py-5`,
      large: tw`py-6`,
      xlarge: tw`py-7`,
      xxlarge: tw`py-8`,
      xxxlarge: tw`py-9`,
    },
  },
  gap: {
    none: {
      // @ts-ignore
      gap: 0,
    },
    xxxsmall: {
      // @ts-ignore
      gap: 4,
    },
    xxsmall: {
      // @ts-ignore
      gap: 8,
    },
    xsmall: {
      // @ts-ignore
      gap: 12,
    },
    small: {
      // @ts-ignore
      gap: 16,
    },
    medium: {
      // @ts-ignore
      gap: 20,
    },
    large: {
      // @ts-ignore
      gap: 24,
    },
    xlarge: {
      // @ts-ignore
      gap: 28,
    },
    xxlarge: {
      // @ts-ignore
      gap: 32,
    },
    xxxlarge: {
      // @ts-ignore
      gap: 36,
    },
  }
}
